version: "3"
services:
  db:
    image: postgres:12.4-alpine
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - local-postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: "pgsql"
      ADMINER_DEFAULT_DB_HOST: "db"
      ADMINER_DEFAULT_DB_NAME: "postgres"

    volumes:
      - ./adminer.css:/var/www/html/adminer.css
volumes:
  local-postgres:
